### ISSUE TITLE
Not enough individuals in the file

### ISSUE THREAD

**Issue by annyyj** [magnusdv/VCFped#3]
Hello，I have one question：
       Four  trios  have analyzed：one result of them was correct；three of them have empty results，*log：Not enough individuals in the file; TRIORES and PAIRRES were NULL
       Would you tell me the reason? Thank you.
       Best wishes

**Comment by magnusdv** [comment]
Hi,
Are all 12 individuals in the same file, or do your have one file for each trio?
In any case, could you share the top part of a variant file that is giving you strange results? Including a few of the variant lines, please. The error message suggests that there may be formatting issues, but I would need a look at the data to say for sure.

**Comment by annyyj** [comment]
[github.zip](https://github.com/magnusdv/VCFped/files/3455927/github.zip)

Hi，
I have one file for each trio，I used GATK to convert  three gvcfs to one vcf.
There are 4 files in the package, first 500 lines from variant files
one trio get correct result : Get_the_right_result.vcf
three trios have empty results: no_result_*.vcf
Best wishes.
